language: python
python:
- '2.7.11'
install: pip install -r requirements.txt
script: python -m unittest discover
notifications:
  slack:
    secure: ck4Xsle/p1NXj+30OnJiFMY00zRn4Zm9qRLayZF9K2UShmQ1Nybdov54UwlO0F/qQLag6djLQmqSqtEmbH/Ct3ii0w2vcms1R9A+UGHipwxnroNRI/NxFZnIrMbB0i6/zMv5j4HWDTJvbHvSKaQJMkVtxQMtRKTkHrHfG5V3GWN7ufltIbfoSYU7gJNu4KJjSFBILSwIdDG5WnF1WmrDyVdGUn+MMmOJtCum4ce5m4ZfpyXFaJKpWWwIMPy7LWF0W75ba9O1WtOUFPvETC2m2Ss2riqcZ5eMa3I0gwLRg4IIjXLL8zsUR1TRx8SHEFBB+SrUWwx/LKX/wPvXfPwJXZi3cAVYrh5bLE8L21O/Ag2XfPVp9B67Pqp/wDuhIwhQmPwzyl2M7/Gxh3SNngfYaFSL5Y3w9Z/cAts/2+XbtUXsbNJVcO+9eiqdl2kQsqLTWOGY1d1qUiiMxbJr9PuaXi8dY5rHonUfhogycdLHyLJVXlCmBt2B4gdW9cz5Clr/1GAHCkJ1ay/C73OWExxzkzuqTBXAhdE6IrT7FUuc+ZFK+bc0ChaYr8gzKs8b+mbbOdF8JhQhtIeDeyueY3WWrQDAYc7Sa7zzbCVXyedP02lQg4lVxCAaHn6eDZotnn/Jhwvr41UHpKf9P7yOxrjcwHfZqT9+uKi9UpxMk3EiUxs=