name: etk_env
dependencies:
- ipython=5.3.0=py27_0
- ipython-notebook=4.0.4=py27_0
- jinja2=2.7.3=py27_1
- jsonschema=2.4.0=py27_0
- libsodium=0.4.5=0
- libxml2=2.9.2=0
- libxslt=1.1.28=0
- lxml=3.6.4=py27_0
- markupsafe=0.23=py27_0
- mistune=0.5.1=py27_1
- openssl=1.0.2h=1
- pip=9.0.1=py27_0
- ptyprocess=0.4=py27_0
- pycosat=0.6.1=py27_0
- pygments=2.0.2=py27_0
- python=2.7.12=1
- pyyaml=3.11=py27_0
- pyzmq=14.6.0=py27_0
- readline=6.2=2
- requests=2.11.1=py27_0
- setuptools=26.1.1=py27_0
- sqlite=3.13.0=0
- ssl_match_hostname=3.4.0.2=py27_0
- terminado=0.5=py27_0
- tk=8.5.18=0
- tornado=4.1=py27_0
- wheel=0.29.0=py27_0
- yaml=0.1.4=0
- zeromq=4.0.5=0
- zlib=1.2.8=3
- nb_conda=2.0.0=py27_0
- pip:
  - jsonpath-rw>=1.4.0
  - backports.ssl-match-hostname==3.4.0.2
  - esmre==0.3.1
  - python-dateutil==2.5.2
  - six==1.10.0
  - tldextract>=2.0.2
  - dateparser>=0.5.1
  - cssselect>=1.0.1
  - spacy>=1.7.5
  - landmark_extractor>=0.1.3.1
  - pygtrie>=2.1
  - phonenumbers>=8.3.3
  - inflection>=0.3.1
  - lxml>=3.6.4
  - beautifulsoup4>=4.3
  - chardet>=2.3.0
  - decorator==4.0.10
  - nose2==0.6.4
  - ply==3.9
  - requests-file==1.4
  - scikit-learn==0.18.1
  - scipy
  - numpy
  - kafka-python>=1.3.3
  - digsandpaper>=0.1.4
  - python-logstash>=0.4.6
